### ISSUE TITLE
acesso a pagina do painel pulando as etapas de login ou cadastro

### ISSUE THREAD

**Issue by alecct812** [lizandravieira/Projeto2#1]
Ao tentar acessar a Home Page por meio da URL sem ter realizado o login anteriormente, é possível acessar a página, mas ela não apresenta informações
![image](https://github.com/lizandravieira/Arcos/assets/132586951/0ff9269d-6b8b-4d9a-b1fe-18d328f0fcdf)

**Comment by TheEuri** [comment]
No caso seria a home page do painel logado

**Comment by TheEuri** [comment]
Bug resolvido

`@login_required(login_url="/login/")
def plataforma(request):
    if request.user.is_authenticated:
        return HttpResponse("Plataforma")`
